#pragma config(Motor,  port3,           arm,           tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port5,           armPivot,      tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port6,           drive,         tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port7,           armUpDown,     tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port8,           clawServoA,    tmotorServoContinuousRotation, openLoop, driveLeft)
#pragma config(Motor,  port9,           clawServoB,    tmotorServoContinuousRotation, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int positiveMovementSpeed = 127; // positive movement speed variables
int negativeMovementSpeed = -127; // negative movement speed variables

int highLowSwitch = 1; // variable used to switch motor speed from fast to slow and vice versa

int joystickThreshold = 15; // variable that prevents accidental joystick bumps from moving the robot

task moveRobot() // Will move robot forward and backward with channel 3 movement
{
	while(true)// Program will constantly check for these events //
	{

		int driveVelocity = vexRT[Ch3]; // maps the drive motor direction and speed to channel 3
		int forwards = vexRT[Btn5U]; // maps varaible that moves robot forward to button 6U
		int backwards = vexRT[Btn5D]; //maps variable that moves robot backward to button 5U
		if (!(abs(driveVelocity) < joystickThreshold) && driveVelocity) /* to prevent accidental joystick bumps,
			when the joystick is moved enough, the motor starts */
		{
			motor[drive] = driveVelocity; // sets 'drive' motor direction and speed as driveVelocity
		}
		else
		{
			stopMotor(drive); // if channel 3 is not in use, stop motor 'drive'
		}

	if (forwards)// while button 5U is pressed the motor 'drive' goes at positiveMovementSpeed
		{
			motor[drive] = positiveMovementSpeed;
			wait1Msec(5000);
		}
		else// when Btn5U is released, the motor 'drive' will stop //
		{
			stopMotor(drive);
		}
		if (backwards)// while Btn5D is pressed the motor 'drive' goes at negativeMovementSpeed
		{
			motor[drive] = negativeMovementSpeed;
			wait1Msec(5000);
		}
		else// when Btn5D is released, the motor 'drive' will stop
		{
			stopMotor(drive);
		}
	}
}

task clawMove() // Will open and close each claw using buttons Btn8U, Btn8L, Btn8R, and Btn8D //
{
	while(true)
	{
		if(vexRT[Btn8U])// when Btn8U is pressed, clawServoA will open //
		{
			motor[clawServoA] = 100;
		}

		if(vexRT[Btn8L])// when Btn8L is pressed, clawServoA will close //
		{
			motor[clawServoA] = 0;
		}

		if(vexRT[Btn8R])// when Btn8R is pressed, clawServoB will open //
		{
			motor[clawServoB] = 0;
		}

		if(vexRT[Btn8D])// when Btn8D is pressed, clawServoB will close //
		{
			motor[clawServoB] = 100;
		}
	}
}

task armExtendRetract() // Moves arm forwards and backwards with channel 2 //
{
	while(true)// Program will constantly check for these events //
	{

		int armExtension = vexRT[Ch4]; // maps variable 'armExtension' to channel 4
		int extend = vexRT[Btn6U]; // maps variable 'extend' to Btn6U
		int retract = vexRT[Btn6D]; // maps variabe 'retract' to Btn6D

		if (!(abs(armExtension) < joystickThreshold))
		{
			motor[arm] = armExtension; // the direction and speed of motor 'arm' are determined
		}
		else
		{
			stopMotor(arm); // if the channel 2 joystick is not being used, stop the motor 'arm'
		}

		if (extend)// while Btn5D is pressed, set motor "arm" speed to 127 //
		{
			motor[arm] = positiveMovementSpeed;
			wait1Msec(5000);
		}
		else// once Btn5D is released, the motor will stop //
		{
			stopMotor(arm);
		}
		if (retract)// while Btn6D is pressed, set motor "arm" speed to -127 //
		{
			motor[arm] = negativeMovementSpeed;
			wait1Msec(5000);
		}
		else// once Btn6D is released, the motor will stop //
		{
			stopMotor(arm);
		}

	}
}

task armRotation() // Rotates arm platform with joystick channel 1
{
	while(true)
	{

		int armRotate = vexRT[Ch1]; // sets the speed and direction to rotate the arm to variable armRotate
		int rotateCounterClockwise = vexRT[Btn7R];// sets the held/released value of Btn7R to the variable "rotateRight" //
		int rotateClockwise = vexRT[Btn7L];// sets the held/released value of Btn7L to the variable "rotateLeft" //

		if (!(abs(armRotate) < joystickThreshold))
		{
			motor[armPivot] = armRotate;
		}
		else
		{
			stopMotor(armPivot);
		}
		if (rotateCounterClockwise)// while Btn7R is pressed, set motor "armPivot" speed to 127 (rotates right) //
		{
			motor[armPivot] = positiveMovementSpeed;
			wait1Msec(5000);
		}
		else// once Btn7R is released, the motor will stop //
		{
			stopMotor(armPivot);
		}
		if (rotateClockwise)// while Btn7L is pressed, set motor "armPivot" speed to -127 (rotates left) //
		{
			motor[armPivot] = negativeMovementSpeed;
			wait1Msec(5000);
		}
		else// once Btn7L is released, the motor will stop //
		{
			stopMotor(armPivot);
		}

	}
}

task armUpAndDown()
{
	while(true)
	{
		int armUp = vexRT[Btn7U];
		int armDown = vexRT[Btn7D];
		int upDownJoystick = vexRT[Ch2];

		if (!(abs(upDownJoystick) < joystickThreshold))
		{
			motor[armUpDown] = upDownJoystick; // the direction and speed of motor 'armUpDown' are determined
		}
		else
		{
			stopMotor(armUpDown); // if the channel 2 joystick is not being used, stop the motor 'armUpDown'
		}

		if (armUp)// while Btn5D is pressed, set motor "arm" speed to positiveMovementSpeed //
		{
			motor[armUpDown] = positiveMovementSpeed;
			wait1Msec(5000);
		}
		else// once Btn5D is released, the motor will stop //
		{
			stopMotor(armUpDown);
		}
		if (armDown)// while Btn6D is pressed, set motor "arm" speed to -127 //
		{
			motor[armUpDown] = negativeMovementSpeed;
			wait1Msec(5000);
		}
		else// once Btn6D is released, the motor will stop //
		{
			stopMotor(armUpDown);
		}
	}
}

task speedChange()
{
	while (true)
	{
		if (vexRT[Btn7D] && highLowSwitch == 1)
		{
			positiveMovementSpeed = 63;
			negativeMovementSpeed = -63;
			highLowSwitch *= -1;

		}
		if (vexRT[Btn7D] && highLowSwitch == -1)
		{
			positiveMovementSpeed = 127;
			negativeMovementSpeed = -127;
			highLowSwitch *= -1;

		}
	}
}

task main()
{
	while(true)// run all tasks //
	{
		startTask(moveRobot);// task which moves robot forwards and backwards
		startTask(clawMove);// task which opens and closes the claw
		startTask(armExtendRetract);// task which moves the arm forwards and backwards
		startTask(armRotation);// task which rotates the arm base
		startTask(speedChange);// task which changes the speed of the motors
		startTask(armUpAndDown); // task which moves the arm up and down
	}
}
