#pragma config(Motor,  port6,           drive,         tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           arm,           tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port5,           armPivot,      tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port8,           clawServoA,    tmotorServoContinuousRotation, openLoop, driveLeft)
#pragma config(Motor,  port9,           clawServoB,    tmotorServoContinuousRotation, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int positiveMovementSpeed = 127; // positive movement speed variables
int negativeMovementSpeed = -127; // negative movement speed variables

int highLowSwitch = 1; // variable used to switch motor speed from fast to slow and vice versa

task moveRobot() // Will move robot forward and backward with channel 3 movement
{
	while(true)// Program will constantly check for these events //
	{
		int joystickThreshold = 15; // variable that prevents accidental joystick bumps from moving the robot
		int driveVelocity = vexRT[Ch3]; // sets the drive motor direction and speed to channel 3
		int forwards = vexRT[Btn6U];
		int backwards = vexRT[Btn5U];
		if (!(abs(driveVelocity) < joystickThreshold) && driveVelocity) // to prevent accidental joystick bumps, when the joystick is moved enough, the motor starts
		{
			motor[drive] = driveVelocity;
		}
		else
		{
			stopMotor(drive);
		}

	if (forwards)// while Btn5U is pressed, set motor "drive" speed to 127 //
		{
			motor[drive] = positiveMovementSpeed;
			wait1Msec(5000);
		}
		else// when Btn5U is released, the motor will stop //
		{
			stopMotor(drive);
		}
		if (backwards)// while Btn6U is pressed, set motor "drive" speed to -127 //
		{
			motor[drive] = negativeMovementSpeed;
			wait1Msec(5000);
		}
		else// when Btn6U is released, the motor will stop //
		{
			stopMotor(drive);
		}
	}
}

task clawMove() // Will open and close each claw using buttons Btn8U, Btn8L, Btn8R, and Btn8D //
{
	while(true)
	{
		if(vexRT[Btn8U])// when Btn8U is pressed, clawServoA will open //
		{
			motor[clawServoA] = 100;
		}

		if(vexRT[Btn8L])// when Btn8L is pressed, clawServoA will close //
		{
			motor[clawServoA] = 0;
		}

		if(vexRT[Btn8R])// when Btn8R is pressed, clawServoB will open //
		{
			motor[clawServoB] = 0;
		}

		if(vexRT[Btn8D])// when Btn8D is pressed, clawServoB will close //
		{
			motor[clawServoB] = 100;
		}
	}
}

task armExtendRetract() // Moves arm forwards and backwards with channel 2 //
{
	while(true)// Program will constantly check for these events //
	{
		int joystickThreshold = 15; // variable that prevents accidental joystick bumps from moving the robot
		int armExtension = vexRT[Ch2]; // set the speed and direction of the arm extension/retraction to variable armExtension
		int extend = vexRT[Btn6D];
		int retract = vexRT[Btn5D];

		if (armExtension)
		{
			motor[arm] = armExtension;
		}
		else
		{
			stopMotor(arm);
		}

		if (extend)// while Btn5D is pressed, set motor "arm" speed to 127 //
		{
			motor[arm] = positiveMovementSpeed;
			wait1Msec(5000);
		}
		else// once Btn5D is released, the motor will stop //
		{
			stopMotor(arm);
		}
		if (retract)// while Btn6D is pressed, set motor "arm" speed to -127 //
		{
			motor[arm] = negativeMovementSpeed;
			wait1Msec(5000);
		}
		else// once Btn6D is released, the motor will stop //
		{
			stopMotor(arm);
		}

	}
}

task armRotation() // Rotates arm platform with joystick channel 1
{
	while(true)
	{
		int joystickThreshold = 15; // variable that prevents accidental joystick bumps from moving the robot
		int armRotate = vexRT[Ch1]; // sets the speed and direction to rotate the arm to variable armRotate
		int rotateCounterClockwise = vexRT[Btn7R];// sets the held/released value of Btn7R to the variable "rotateRight" //
		int rotateClockwise = vexRT[Btn7L];// sets the held/released value of Btn7L to the variable "rotateLeft" //

		if (armRotate)
		{
			motor[armPivot] = armRotate;
		}
		else
		{
			stopMotor(armPivot);
		}
		if (rotateCounterClockwise)// while Btn7R is pressed, set motor "armPivot" speed to 127 (rotates right) //
		{
			motor[armPivot] = positiveMovementSpeed;
			wait1Msec(5000);
		}
		else// once Btn7R is released, the motor will stop //
		{
			stopMotor(armPivot);
		}
		if (rotateClockwise)// while Btn7L is pressed, set motor "armPivot" speed to -127 (rotates left) //
		{
			motor[armPivot] = negativeMovementSpeed;
			wait1Msec(5000);
		}
		else// once Btn7L is released, the motor will stop //
		{
			stopMotor(armPivot);
		}

	}
}

task speedChange()
{
	while (true)
	{
		if (vexRT[Btn7D] && highLowSwitch == 1)
		{
			positiveMovementSpeed = 63;
			negativeMovementSpeed = -63;
			highLowSwitch *= -1;
			
		}
		if (vexRT[Btn7D] && highLowSwitch == -1)
		{
			positiveMovementSpeed = 127;
			negativeMovementSpeed = -127;
			highLowSwitch *= -1;
			
		}
	}
}


task main()
{
	while(true)// run all tasks //
	{
		startTask(moveRobot);// task which moves robot forwards and backwards
		startTask(clawMove);// task which opens and closes the claw
		startTask(armExtendRetract);// task which moves the arm forwards and backwards
		startTask(armRotation);// task which rotates the arm base
		startTask(speedChange);// task which changes the speed of the motors
	}
}
